title: Random Thoughts
name: "Zhanxiong's Blog"
author: Zhanxiong Xu
twitter_username: hugebear
baseurl: "/my-log"
description: Document my learning notes.
profile_url: "http://littlecottage.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  toc_levels: 1..4
